version: "3.8"
services:
  frontend:
    build: ./frontend/sreality-scraper
    ports:
      - 8080:8080
    depends_on:
      - db
      - backend

  backend:
    build: ./server
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
